USE [master]
GO

/****** Object:  Database [GameReviews]    Script Date: 6/23/2023 9:34:42 PM ******/
CREATE DATABASE [GameReviews]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GameReviews', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\GameReviews.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GameReviews_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\GameReviews_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GameReviews].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GameReviews] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GameReviews] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GameReviews] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GameReviews] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GameReviews] SET ARITHABORT OFF 
GO

ALTER DATABASE [GameReviews] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [GameReviews] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GameReviews] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GameReviews] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GameReviews] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GameReviews] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GameReviews] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GameReviews] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GameReviews] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GameReviews] SET  ENABLE_BROKER 
GO

ALTER DATABASE [GameReviews] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GameReviews] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GameReviews] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GameReviews] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GameReviews] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GameReviews] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [GameReviews] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GameReviews] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GameReviews] SET  MULTI_USER 
GO

ALTER DATABASE [GameReviews] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GameReviews] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GameReviews] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GameReviews] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GameReviews] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GameReviews] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GameReviews] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GameReviews] SET  READ_WRITE 
GO

